import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import Feed from '../components/Feed'
import Widgets from '../components/Widgets' 

export default function Home() {
  return (
    <div className="lg:max-w-6xl mx-auto max-h-screen overflow-hidden">
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
      
      </Head>

      <main className="grid grid-cols-9">
       <Sidebar/>
<Feed/>     
<Widgets/>  
</main>
        
    </div>
  )
}
